-
  name: Deploy Simple Web Application
  hosts: db_web_server
  tasks:
    - name: Update Repository
      apt:
        update_cache: true
      become: yes

    - name: Install python-pip
      apt: name=python3-pip state=present
      become: yes

    - include: tasks/deploy_db.yml

    - include: tasks/deploy_web.yml
