-
  name: Deploy Simple Web Application
  hosts: db_web_server
  vars:
    db_name: employee_db
    db_user: db_user
    db_password: Passw0rd
  tasks:
    - name: Update Repository
      apt:
        update_cache: true
      become: yes

    - name: Install python-pip
      apt: name=python3-pip state=present
      become: yes

    - name: Install MySQL
      apt: name=mysql-server state=present
      become: yes

    - name: Install MySQL
      apt: name=mysql-client state=present
      become: yes

    - name: Start and Enable mysql service
      service: name=mysql state=started enabled=yes
      become: yes

    - name: install pymysql
      pip:
        name: PyMySQL
        # executable: pip3
      become: yes

    # - name: create root user password
    #   mysql_user:
    #     name: 'root'
    #     password: "{{ db_password }}"
    #     priv: '*.*:ALL,GRANT'
    #     host: 'localhost'
    #     login_unix_socket: /var/run/mysqld/mysqld.sock
    #     state: present
    #   become: yes

    - name: create database
      mysql_db:
        name: '{{ db_name }}'
        state: present
        login_user: 'root'
        login_password: '{{ db_password }}'
      become: yes

    - name: create db user
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        host: '%'
        priv: '*.*:All'
        state: present
        login_user: 'root'
        login_password: '{{ db_password }}'
      become: yes

    - name: copy file
      copy: src=app.py dest=/opt/app.py
      become: yes

    - name: install flask and dependencies
      pip: name={{ item }} state=present
      with_items:
        - flask
        - flask-mysql
      become: yes

    - name: start Application
      command: FLASK_APP=/opt/app.py flask run --host=0.0.0.0
