    - name: copy file
      copy: src=app.py dest=/opt/app.py
      become: yes

    - name: install flask and dependencies
      pip: name={{ item }} state=present
      with_items:
        - flask
        - flask-mysql
      become: yes

    - name: start Application
      command: FLASK_APP=/opt/app.py flask run --host=0.0.0.0
